### ISSUE TITLE
How to add an App ?

### ISSUE THREAD

**Issue by BattleHook** [lgfrbcsgo/wot-battle-results-server#1]
Like your project. Thx for sharing this with us.

You have added 2 example App's. But how can I create my own App ?
Thank you in advance to elaborate on this matter.

**Comment by lgfrbcsgo** [comment]
You can copy the code of one of the sample apps to use as your starting point.

If you haven't created a web app before, there are a lot of tutorials on how to get started with JavaScript and WebSockets.

Once you have deployed your app somewhere, I can add it to the allowed origins and publish an update of the mod.

**Comment by BattleHook** [comment]
Correct me if I am wrong:
in order to create my own test environment:
1) I copy the example apps on my NAS (Synology running a webserver)
2) I have to edit server.py (in the wot.mod file (lgfrbcsgo.battle-results-server_1.0.3.wotmod\res\scripts\client\mod_battle_results_server) and change the ORIGIN_WHITELIST "https://lgfrbcsgo.github.io" to for example "https://mysynology url/basedir"
3) compile server.py to server.pyc
4) update the wotmod with the new server.pyc
5) start World of Tanks with the battle_results_server mod
6) then try to create and test my own App.

**Comment by lgfrbcsgo** [comment]
Yes, that would work. 

However I would recommend running a local webserver instead of hosting it on your NAS. 
That should make development much easier and you wouldn't need to edit the mod.

`localhost` is white listed by default.

If you have Python installed on your PC, you can start a lightweight HTTP server on `localhost` without having to install anything.

Python3:
`python -m http.server 8000`
https://docs.python.org/3/library/http.server.html

Python2: 
`python -m SimpleHTTPServer 8000`
https://docs.python.org/2/library/simplehttpserver.html
